all:
	g++ 1.cpp -lUrho3D -g -O2 -D__DEBUG__
and:
	aarch64-linux-android26-clang++ 1.cpp  -shared -lUrho3D -I/home/user/Android/Sdk/ndk-bundle/sysroot/usr/include/ -L /home/user/Android/Sdk/ndk-bundle/sysroot/usr/lib/aarch64-linux-android/ -o out.so
